name: 'Create release'
description: > 
  Create release notes json file specific to gudiewire application
author: 'FBITN DevOps Team'
inputs:
  RELEASE_VERSION: 
    description: The version of release to add as revision
    required: false
  ASSET_PACKAGE_NAME: 
    description: Name of the package which has the prod-release-notes.json file in the latest release
    required: false
  OUTPUT_FILE: 
    description: The output file for trunk release notes
    required: false
  GIT_TOKEN: 
    description: GitHub token for authentication
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Generate trunk build release notes
      shell: bash
      if: startsWith(github.ref_name, 'main')
      env:
        GH_TOKEN: ${{ inputs.GIT_TOKEN }}
        OUTPUT_FILE: ${{ inputs.OUTPUT_FILE }}
      run: |
        bash ${{ github.action_path }}/scripts/generate-trunk-build-notes.sh

    - name: Commit and push trunk release notes
      shell: bash
      if: startsWith(github.ref_name, 'main')
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

        cat ${{ inputs.OUTPUT_FILE }}

        git add ${{ inputs.OUTPUT_FILE }}

        # Only commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: update release notes [skip ci]"
          git push
        fi
    - name: Generate release build release notes
      shell: bash
      if: startsWith(github.ref_name, 'release/')
      env:
        GH_TOKEN: ${{ inputs.GIT_TOKEN }}
        RELEASE_VERSION: ${{ inputs.RELEASE_VERSION }}
        PACKAGE_NAME: ${{ inputs.ASSET_PACKAGE_NAME }}
      run: |
        bash ${{ github.action_path }}/scripts/generate-release-build-notes.sh
