name: 'Create release'
description: > 
  Create release notes json file specific to gudiewire application
author: 'TEST-IW'
inputs:
  RELEASE_VERSION: 
    description: The version of release to add as revision
    required: false
  OUTPUT_FILE: 
    description: The output file for trunk release notes
    required: false
  
runs:
  using: "composite"
  steps:
    - name: Generate trunk build release notes
      shell: bash
      if: startsWith(github.ref_name, 'main')
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FILE: ${{ inputs.OUTPUT_FILE }}
      run: |
        bash ${{ github.action_path }}/scripts/generate-trunk-build-notes.sh

    - name: Commit and push trunk release notes
      shell: bash
      if: startsWith(github.ref_name, 'main')
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add release-notes/${{ steps.build-type.outputs.output_file }}

        # Only commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: update release notes [skip ci]"
          git push
        fi
    - name: Generate release build release notes
      shell: bash
      if: startsWith(github.ref_name, 'release/**')
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_VERSION: ${{ inputs.RELEASE_VERSION }}
      run: |
        bash .github/scripts/generate-release-build-notes.sh
